"""
Django settings for site1 project.

Generated by 'django-admin startproject' using Django 4.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

import os
from pathlib import Path

#New Logger
# from .logging_config import RequestLogFilter

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-(*x+aa&c41r1b28mgq3!ax6-)p!2r4-2ntu7a=%2^ez5tt+r+a'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    "ExamsPlatform.apps.ExamsplatformConfig",
    "StudentsInfo.apps.StudentsinfoConfig",
    "ClassroomsPlatform.apps.ClassroomsplatformConfig",
    "AssignmentPlatform.apps.AssignmentplatformConfig",
    "Frontend.apps.FrontendConfig",
    "ManagementApp.apps.ManagementappConfig",
    'jazzmin',
    'django_crontab',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders', 
    'drf_yasg',
    # 'jalali_date',
    # 'debug_toolbar',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    # 'site1.CustomMiddlewares.LoggingMiddleware',
    # 'debug_toolbar.middleware.DebugToolbarMiddleware',############
    
]

ROOT_URLCONF = 'site1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['./templates',],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'site1.wsgi.application'
# ASGI_APPLICATION = 'site1.asgi.application'
REST_FRAMEWORK ={
    'DEFAULT_AUTHENTICATION_CLASSES':(
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES':(
        'rest_framework.permissions.IsAuthenticated',        
        # 'rest_framework.permissions.AllowAny',
    ),
    'DEFAULT_FILTER_BACKENDS':(
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ),
    # 'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.LimitOffsetPagination','PAGE_SIZE':10
    'DEFAULT_PAGINATION_CLASS':'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE':10
}

# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

### Normal DB Configs

# DATABASES = {  
#     'default': {  
#         'ENGINE': 'django.db.backends.mysql',  
#         'NAME': 'mindesca_arash',  
#         'USER': 'mindesca_attar',  
#         'PASSWORD': 'hCgr7=^pmFAwk9%X',  
#         'HOST': '127.0.0.1',  
#         'PORT': '3306',  
#         'OPTIONS': {  
#             'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
#             'charset': 'utf8mb4'
#         }  
#     }  
# } 

# CACHES = {
#     "default": {
#         "BACKEND": "django_redis.cache.RedisCache",
#         "LOCATION": "unix:/home/arashat1/redis/redis.sock?db=0",
#         "OPTIONS": {
#             "CLIENT_CLASS": "django_redis.client.DefaultClient",
#         }
#     }
# }


### RUNFLARE DB Configs

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'maindbgqw_db',
        'USER': 'postgres',
        'PASSWORD': 'ps!evVUpoRRj6vYN26Zf',
        'HOST': 'maindb-mfw-service',
        'PORT': '5432',
    }
}

CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://default:qO33pfoBp$2NfXNhSoBo@cachedb-ign-service:6379/0",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}

SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "default"

# CELERY_BROKER_URL = "redis://default:qO33pfoBp$2NfXNhSoBo@cachedb-ign-service:6379/0"


CRONJOBS = [
    ('*/0 * * * *', 'ExamsPlatform.exam_release')
]
# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    # {
    #     'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    # },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    # },
    # {
    #     'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    # },
]

CORS_ORIGIN_WHITELIST = [
     'http://localhost:3000'
]
CORS_ALLOWED_ORIGINS = [
    "https://www.kevin.mindescape.co",
    "https://kevin.mindescape.co",
    "https://www.lab.mindescape.co",
    "https://lab.mindescape.co",
    "https://www.arash-attar.com",
    "https://arash-attar.com",
    "https://api.arash-attar.com",
    'http://localhost:3000',
]
    # "http://www.arash-attar.com",
    # "http://arash-attar.com",
    # "http://api.arash-attar.com",

JALALI_DATE_DEFAULTS = {
   'Strftime': {
        'date': '%y/%m/%d',
        'datetime': '%H:%M:%S _ %y/%m/%d',
    },
    'Static': {
        'js': [
            # loading datepicker
            'admin/js/django_jalali.min.js',
            # OR
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.core.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/calendar.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc.js',
            # 'admin/jquery.ui.datepicker.jalali/scripts/jquery.ui.datepicker-cc-fa.js',
            # 'admin/js/main.js',
        ],
        'css': {
            'all': [
                'admin/jquery.ui.datepicker.jalali/themes/base/jquery-ui.min.css',
            ]
        }
    },
}

# SWAGGER_SETTINGS = {
#     'ACCEPT_HEADER_VERSION': {
#         'AcceptHeaderVersioning': {
#             'version': 'CUSTOM_HEADERS'
#         }
#     },
# }

SWAGGER_SETTINGS = {
        'SECURITY_DEFINITIONS': {
            'api_key':{
                'type': 'apiKey',
                'in': 'header',
                'name': 'Authorization',
            }
        }
}


# CORS_ORIGIN_ALLOW_ALL = True
LOGIN_REDIRECT_URL = '/accounts/'
# AUTH_USER_MODEL = 'StudentsInfo.StudentUser'
# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Tehran'

USE_I18N = True

USE_TZ = True

SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE =True
SESSION_EXPIRE_AT_BROWSER_CLOSE = True
SECURE_SSL_REDIRECT = True
##
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_HSTS_SECONDS = 15768000
SESSION_COOKIE_SECURE = True
CSRF_COOKIE_SECURE = True
X_FRAME_OPTIONS = 'DENY'

##

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

LOGGING = {
    'version': 1,
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'info.log',
        },
    },
    'loggers': {
        '': {
            'handlers': ['file'],
            'level': 'INFO',
        },
    },
}




# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'filters': {
#         'add_request_info': {
#             '()': RequestLogFilter,
#         },
#     },
#     'formatters': {
#         'detailed': {
#             'format': '{asctime} {levelname} USER: {username} URL: {url} MESSAGE: {message}',
#             'style': '{',
#         },
#         'simple': {
#             'format': '{asctime} {levelname} {message}',
#             'style': '{',
#         },
#     },
#     'handlers': {
#         'console': {
#             'level': 'ERROR',
#             'class': 'logging.StreamHandler',
#             'formatter': 'detailed',
#             'filters': ['add_request_info'],
#             'stream': 'ext://sys.stderr',
#         },
#         'file': {
#             'level': 'INFO',
#             'class': 'logging.FileHandler',
#             'filename': 'info.log',
#             'formatter': 'simple',
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['console', 'file'],
#             'level': 'INFO',
#             'propagate': True,
#         },
#         'django.request': {
#             'handlers': ['console'],
#             'level': 'ERROR',
#             'propagate': False,
#         },
#     },
# }



DATA_UPLOAD_MAX_MEMORY_SIZE = 52428800  # 10 MB, adjust as needed
FILE_UPLOAD_MAX_MEMORY_SIZE = 52428800
# STATIC_URL = '/static/'
STATIC_URL = '/Collected/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'Storage/staticfiles')

MEDIA_ROOT = os.path.join(BASE_DIR, 'Storage')
MEDIA_URL = '/Storage/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
